[package]
name = "static_assets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
entry = { path = "../entry" }

color-eyre = "0.6.2"
tracing = "0.1.37"
