[package]
name = "entry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sql = { path = "../sql" }

color-eyre = "0.6.2"
ignore = "0.4.20"
tracing = "0.1.37"
seahash = "4.1.0"
rusqlite = "0.29.0"
