[package]
name = "site"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
content = { path = "../content" }
config = { path = "../config" }
markdown = { path = "../markdown" }
entry = { path = "../entry" }
sql = { path = "../sql" }
static_files = { path = "../static_files" }
assets = { path = "../assets" }

color-eyre = "0.6.2"
rusqlite = "0.31.0"
tera = "1.19.1"
tracing = "0.1.37"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
chrono = "0.4.31"
