[package]
name = "site"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entry = { path = "../entry" }
content = { path = "../content" }
sass = { path = "../sass" }
color-eyre = "0.6.2"
ignore = "0.4.20"
rusqlite = "0.28.0"
tera = "1.18.0"
tracing = "0.1.37"
